# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bidders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biddingID', models.IntegerField()),
                ('userID', models.IntegerField()),
                ('bidPrice', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('biddingID', models.AutoField(primary_key=True, serialize=False)),
                ('propertyID', models.IntegerField()),
                ('startPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('CurPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ownerID', models.IntegerField()),
                ('dateStart', models.DateTimeField()),
                ('dateEnd', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Bidlet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('property', models.CharField(max_length=200, unique=True)),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('propertyID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=250)),
                ('ownerID', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postalCode', models.CharField(max_length=6)),
                ('suite', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(max_length=200)),
                ('startPrice', models.DecimalField(decimal_places=2, max_digits=8)),
                ('biddingID', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
